const ConstantTypes = {
    ADD_INGRDIENT:'ADD_INGRDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    UPDATE_PRICE: 'UPDATE_PRICE',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    FETCH_INGRDIENTS_FAILED: 'FETCH_INGRDIENTS_FAILED',
    PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAILED: 'PURCHASE_BURGER_FAILED',
    PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
    PURCHASE_INIT: 'PURCHASE_INIT',
    FETCH_ORDERS_START: 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS: 'FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAIL: 'FETCH_ORDERS_FAIL'

};

export default ConstantTypes;